version: '3.7'
services:

  debugpy:
    build:
      context: .
    ports:
      - 5678:5678
    env_file:
      - .env
    entrypoint: /bin/sh
    command: -c "pip install debugpy && python -m debugpy --wait-for-client --listen 0.0.0.0:5678 ."
